image: node:latest

pages:
  stage: deploy
  cache:
    paths:
    - node_modules/
  only:
  - master
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
      - public