# Site settings
name: Carl Amko 
email: carl@carlamko.me
canonical_url: https://carlamko.me
keywords: "Software Engineer, Python, Go, Java, AI, Kubernetes, AWS"
skills: "Software Engineer in Denver, CO"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: github
    url: https://github.com/CarlAmko
  - title: pencil
    url: https://basicbytes.dev
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
