baseurl = "http://carlamko.me/blog"
title = "Blogs"
languageCode = "en-us"
theme = "hugo-theme-bleak"
[params]
  logo = ""
  cover = "http://wallpapercave.com/wp/WaFOpxG.jpg"
  disqus_identifier = "carlamko"
  dev = true
